### ISSUE TITLE
Couldn't find enough finder patterns

### ISSUE THREAD

**Issue by lukeIam** [edi9999/jsqrcode#15]
I'm always getting 
`Couldn't find enough finder patterns:0 patterns found`
or
`Couldn't find enough finder patterns:1 patterns found`
sometimes even 
`Couldn't find enough finder patterns:2 patterns found`

Video resolution is 800x450 and the imagedata looks good:
![qr](https://cloud.githubusercontent.com/assets/5115160/14232664/f548fb6a-f9b1-11e5-85c6-baca2725f06e.png)
Captured with: `previewCtx.putImageData(ctx.getImageData(0, 0, width, height), 0, 0);`

If I load the image data from a img element with a barcode image it is working -> so my general setup with the web worker is working.

Any suggestions?

**Comment by edi9999** [comment]
Hi, I don't really know why this is happening (I just ported the library to nodejs and added some test cases). But if you find out, it would be cool to add a regression test and the code to fix it (I would of course accept the pull request)

**Comment by edi9999** [comment]
Closed via https://github.com/edi9999/jsqrcode/pull/21
