### ISSUE TITLE
Latest commits not converged on npm.

### ISSUE THREAD

**Issue by RichardsonWilliam** [edi9999/jsqrcode#22]
The last update has not changed the project in [npm](https://www.npmjs.com/package/qrcode-reader).

I have little knowledge of NPM. This seems easy to do, but, how? I left something to do in my commits? Can you suggest some learning books or articles?

**Comment by edi9999** [comment]
I will publish à new version when i i'm on my main computer in 13 hours

**Comment by RichardsonWilliam** [comment]
SGTM!
This can not be automated?

**Comment by edi9999** [comment]
I haven't ever seen a project automating the npm publishing, it would require me to put my npm keys somewhere. It is now published as npm version 0.2.1
