### ISSUE TITLE
Extraneous Parameters Passed

### ISSUE THREAD

**Issue by Xanir** [edi9999/jsqrcode#3]
A lot of method take in both *image* and *qrcode*.

As qrcode contains *image* it is not needed.
A cleaner parameter would be to pass the original ImageData object acquired from the Canvas, or a single object that contains the array and the height / width

**Comment by edi9999** [comment]
Altough i agree, i don't have time to change this. I would accept a pull request

**Comment by edi9999** [comment]
Fixed for real now #5 , I won't close if it isn't from now
