### ISSUE TITLE
More code

### ISSUE THREAD

**Issue by rugk** [edi9999/jsqrcode#36]
FYI you could also include https://github.com/wojciechszela/zxingjs by @wojciechszela or join forces if it helps you to maintain this lib.

**Comment by edi9999** [comment]
Yes, if @wojciechszela , you want to help on this project you're welcome !

**Comment by rugk** [comment]
Just thought you could also grab some code… :wink: 

No seriously, nevermind. I just wanted to let you both know.

**Comment by wojciechszela** [comment]
You can grab the code from my repo. Feel free to do so. I'm happy to navigate you through it. I've just lost interest after Mozilla announced the termination of their Firefox OS phones project, so I won't be contributing to my port but I'm happy to help if someone wants to reuse some code or take the project over.
