### ISSUE TITLE
QRCode Classed defined on Window

### ISSUE THREAD

**Issue by Xanir** [edi9999/jsqrcode#4]
All of the classes defined within the library are defined on the Window.
To ensure they do not cause conflict or pollute the Window object they should be contained within the qrcode object.

**Comment by edi9999** [comment]
Altough i agree, i don't have time to change this. I would accept a pull request

**Comment by Xanir** [comment]
Closing this because you yourself cannot implement it does not seem fair as the issues itself is not resolved.
I have been working on changes for this issue as well other changes to make the API more usable so I was also polling how active this project is.

**Comment by edi9999** [comment]
Fixed for real on #5
