### ISSUE TITLE
Image is not defined

### ISSUE THREAD

**Issue by Ethan0007** [edi9999/jsqrcode#44]
Hi,

I'm using react-native and I'm trying to decode bar-code base on the camera result and follow the docs instruction, but when i call the qr.decode(data.path) it will give me an exception . "Image is not define";

Please be advised.
#Thanks

**Comment by hponcet** [comment]
Hi,
Same problem for me.

**Comment by edi9999** [comment]
This means that you are not using the right data format. 

In nodejs, you have to pass an image buffer .

See the tests for details 

https://github.com/edi9999/jsqrcode/blob/master/test/qrcode.js

**Comment by Shery11** [comment]
Hi, 
I am encountering the same issue, i am generating a qr code using another library its gives me url of qrcode which is base64 encoded. I am passing it ;ike this  qr.decode(url) l n i am getting this error Image is not defined 

Any suggestions?

**Comment by eriforce** [comment]
Hi,
I am encountering the same issue when decoding from an url.

**Comment by edi9999** [comment]
You have to parse your image with image-parser first
