### ISSUE TITLE
image-parser is not defined

### ISSUE THREAD

**Issue by azayneeva** [edi9999/jsqrcode#45]
Node throws error that it cannot find module 'image-parser'

**Comment by edi9999** [comment]
Did you try doing 

`npm install --save image-parser` ?

As far as I know, the only place where we use image-parser is in the tests file, so I don't see how you get this error by just using the library.

**Comment by azayneeva** [comment]
npm install --save image-parser seems not to work on node 8 (checking if it's something else).
It is only used in the test but I don't see any example about hot to read an actual image unless it's already png64 encoded in the docs

**Comment by edi9999** [comment]
I have updated the readme with info about how to get it working on node with `jimp` (easiest) and `image-parser` (needs graphicsmagick)

See here : 
https://github.com/edi9999/jsqrcode#passing-image-data-in-node

**Comment by azayneeva** [comment]
Thank you a lot!
