### ISSUE TITLE
Invalid mode: 7 in (block:0 bit:3)

### ISSUE THREAD

**Issue by adrianmarinica** [edi9999/jsqrcode#47]
Hey!

First off, great job with maintaining this project! 

Secondly, I've stumbled on a small issue when trying to decode QR codes generated with zxing, `Invalid mode: 7 in (block:0 bit:3)`.

I've found this issue mentioned in LazarSoft's repo, https://github.com/LazarSoft/jsqrcode/issues/33

In there, somebody proposes a simple solution, that I could easily PR, but before that, I wanted to know if you are aware of it, if you plan on adding that fix yourself, etc. 

What do you think?

Thanks!

**Comment by edi9999** [comment]
I haven't looked at the issue for now, but totally ok to merge a PR.

If possible, can you include a test that fails before the code change ?

**Comment by adrianmarinica** [comment]
Sorry for the late response. I have created a PR (https://github.com/edi9999/jsqrcode/pull/48) for this issue. 

Checking out the first commit should demonstrate the issue, while the extra check added in the second commit should show how this issue would be solved.

If there is anything wrong with the code that should be changed, let me know and I will update the PR.

Thanks!

**Comment by edi9999** [comment]
Thanks, looks good to me !

**Comment by adrianmarinica** [comment]
Awesome! Do you have plans for a new NPM release with this change?

**Comment by edi9999** [comment]
Released in 1.0.4

**Comment by adrianmarinica** [comment]
Thanks!
