### ISSUE TITLE
Draw a Rectange around the Recognized Code...

### ISSUE THREAD

**Issue by jogibear9988** [edi9999/jsqrcode#51]
Is it possible to get the size, position and angle of the rect were the Barcode is found, to draw a rectangle around it (see here: https://serratus.github.io/quaggaJS/examples/live_w_locator.html)

**Comment by edi9999** [comment]
Yes that is possible, the result of the qrcode processing returns x/y coordinates for each "module"

```
  "result": 'Test',
  "points": [
    {
      "count": 2,
      "estimatedModuleSize": 8,
      "x": 36,
      "y": 148,
    },
    {
      "count": 2,
      "estimatedModuleSize": 8,
      "x": 36,
      "y": 36,
    },
    {
      "count": 2,
      "estimatedModuleSize": 8,
      "x": 148,
      "y": 36,
    }
  ]
```

**Comment by jogibear9988** [comment]
And the Angle? Or is it not possible to scan rotated?

**Comment by edi9999** [comment]
It is possible to scan a rotated qrcode. 

From the position of the three points, you should be able to draw a triangle and get the angle from that.
