### ISSUE TITLE
Include in QuaggaJs

### ISSUE THREAD

**Issue by jogibear9988** [edi9999/jsqrcode#52]
Wouldn't it be a good effort, if we try to include this lib into quaggaJs, so we get one lib for all barcodes?

**Comment by edi9999** [comment]
I don't think that would be so easily possible, both jsqrcode and QuaggaJS have quite big codebases. 
I also prefer to have multiple small libraries than a big one that does too many different things. 
Mainly because smaller makes it more maintainable.
