### ISSUE TITLE
Phonegap

### ISSUE THREAD

**Issue by julie78990** [edi9999/jsqrcode#6]
Hi,
I'm looking for a QR Code scanner and I would like to know if you ever have tried the plugin in a phonegap project? I tried another plugin which was using Jquery but didn't manage to get it work with phonegap.
Thanks in advance

**Comment by edi9999** [comment]
The library takes a data URL as input. If you find out how to get the image from the camera in that format from inside phonegap, I'm very confident that the jsqrcode part will work (because it already works in mobile browsers I think)
