### ISSUE TITLE
__defineGetter__ depricated

### ISSUE THREAD

**Issue by limpbrains** [edi9999/jsqrcode#7]
IE 10 and IE9 fails with error:
```
Object doesn't support property or method '__defineGetter__' 
```

Looks like [defineGetter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__) is depricated and should be replaced with [defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

Also there is a workaround with polyfill: http://blogs.msdn.com/b/ie/archive/2010/09/07/transitioning-existing-code-to-the-es5-getter-setter-apis.aspx

**Comment by edi9999** [comment]
Solved by b596a47d17e9cfb60b7a18cefaeb0fcb69266230
