### ISSUE TITLE
Usage is not intuitive

### ISSUE THREAD

**Issue by databaseindays** [edi9999/jsqrcode#9]
I can't figure out how to even run the included test.html it has none of the code specified in your USAGE: section. Im on local ubuntu environment and all I see when I run test.html is a button that says capture and a box with a dashed border. no camara shown and button does nothing. im thinking I should see a demo of the code in action but nothing. Is code working for anyone?

**Comment by edi9999** [comment]
you can have a look at https://github.com/edi9999/jsqrcode/blob/master/test/qrcode.js

**Comment by databaseindays** [comment]
thanks, I know you are trying to be helpful, but I dont get it, where does
this go? surely it is easy for you to just provide a working demo file(s) ,
with all the code that works right?

thanks

Norman

On Sun, Nov 15, 2015 at 5:15 AM, Edgar Hipp <notifications@github.com>
wrote:

> you can have a look at
> https://github.com/edi9999/jsqrcode/blob/master/test/qrcode.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edi9999/jsqrcode/issues/9#issuecomment-156798909>.
>



-- 
Thanks,

Norman

**Comment by edi9999** [comment]
Sorry, there's no demo of the code in the browser. I might add it in the future.

To use this module in the browser, I recommend you to have a look at browserify

**Comment by edi9999** [comment]
Kudos to @backflip for finally adding an online demo : (See https://github.com/edi9999/jsqrcode/pull/16)
